version: "3.9"

services:
  dev:
    image: "node:10"
    ports:
      - "8888:8000"
    volumes:
      - ./:/app
    command: "/bin/bash"
    working_dir: "/app"

  server:
    image: "node:10"
    ports:
      - "8888:8000"
    volumes:
      - ./:/app
    command: "node test.js"
    working_dir: "/app"  